### ISSUE TITLE
Google pagespeed module in apache docker image

### ISSUE THREAD

**Issue by akshayat** [bitnami/bitnami-docker-apache#101]
Bitnami's LAMP stack and wordpress stack (I assume others too) add Google's pagespeed module in apache while installation;

However it seems apache's docker image doesn't include that?

Is there any way to include pagespeed module? 

I cannot use the deb package offered by Google as it require apache as a service installed.

**Comment by faberdev** [comment]
I am also trying to install a module for the Apache image and try to do so with `command:` in the `docker-compose` file. This after the image is built. Not happy about that. Made an issue about this [here](https://github.com/bitnami/bitnami-docker-apache/issues/100).

Indeed, having the pagespeed module installed would be very good. If you find a way to install additional modules kindly do let me know. I am also keeping an eye on any progress of this issue. Thank you.

In general, having a script from Bitnami that could install additional modules for this image would be excellent.

**Comment by robots4life** [comment]
I am also trying to install a module for the Apache image and try to do so with `command:` in the `docker-compose` file. This after the image is built. Not happy about that. Made an issue about this [here](url) asking for help with that.

Indeed, having the pagespeed module installed would be very good. If you find a way to install additional modules kindly do let me know. I am also keeping an eye on any progress of this issue. Thank you.

In general, having a script from Bitnami that could install additional modules for this image would be excellent.

**Comment by simpleenigma** [comment]
I just did a multi-stage build over the weekend to do exactly this.

[Dockerfile.txt](https://github.com/bitnami/bitnami-docker-apache/files/4504297/Dockerfile.txt)

**Comment by robots4life** [comment]
@simpleenigma Nice one, thank you!

Very new to Docker and all here. My docker-compose looks like this.
[docker-compose.yml.txt](https://github.com/bitnami/bitnami-docker-apache/files/4504340/docker-compose.yml.txt)

1. Where how can I include that modified build into the docker-compose file please?

2. Will the original image bitnami-docker-apache still have all the correct config and security settings as done by Bitnami?

I am trying to build a custom [LAMP stack](https://docs.bitnami.com/containers/how-to/create-amp-environment-containers/) **with** extra modules for various images while resorting to proven solid tested images that take as much as possible of the configuration and security away from me.

Thank you for any more help with how to use your Dockerfile.
Learning about `multi-stage` builds now.. if this works, this is very nice!
Because that means I could also include the aclr2 module like this.
Thank you! :+1: :100:

**Comment by simpleenigma** [comment]
As I understand it, the multi-stage build restarts from the second FROM line and has only the changes from there. I set up a conf folder that has the same structure as the Bitnami structure and includes my config for pagespeed.conf so that I can have the new config file. I also need my system to use UID 48 of legacy reasons and I have the new image set up to run as root instead of a user.

If you take out all of the USER and RUN lines after the second FROM but keep the COPY lines it will behave exactly like the original image with pagespeed installed. (Note: I think I had an issue with the pagespeed log folder that I got past with the USER root line. This is a better way to do that, but I am prototyping ATM)

FYI: I'm not using docker-compose, so I can't address that directly. 

FYI: In working with multi-stage builds with PHP and adding PECL modules I had to copy some .so files and then add lines to link them properly. I finally got a good PHP 7.x image with sqlsrv build working. Now I have running images for PHP 7.2, 7.3 and 7.4 using this technique. It is very powerful.

**Comment by robots4life** [comment]
@simpleenigma Thank you for the explanations. Much I can learn from that. I will go over in more detail what all that means and see how `multi-stage` builds can extend the base image.

Good to know I can keep the modification to the Apache base image as small as possible while also being able to add more modules to Apache.

You mention PECL. That is what I will try and do next. [Installing the Imagick extension with WebP support in PHP](https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension-with-WebP-support). So also thank you for mentioning that. I see this `multi-stage` procedure is indeed powerful.

Do you have a repo with your Dockerfiles somewhere? Seems like I could use those for help in getting a decent LAMP stack going. :smile:

**Comment by simpleenigma** [comment]
This will be a gold mine fo you then. Not perfect, but good enough. The sqlsrv is worth it if you need to access MSSQL as my system does. notice the cgi-fcgi lines in there, I'm using that for very basic health checks.

[Dockerfile.txt](https://github.com/bitnami/bitnami-docker-apache/files/4504576/Dockerfile.txt)

My repos are currently private on AWS while I develop the next generation fo my system.

**Comment by robots4life** [comment]
Thank you indeed.
I see a lot of things in there that will come in very handy. :dark_sunglasses:

**Comment by akshayat** [comment]
> I just did a multi-stage build over the weekend to do exactly this.
> 
> [Dockerfile.txt](https://github.com/bitnami/bitnami-docker-apache/files/4504297/Dockerfile.txt)

I also achieved that using multi stage build, see [here](https://stackoverflow.com/a/61276740/1534925)

@simpleenigma I think you would also want to copy the conf files from build stage. 

Still not sure it is the correct way or not.

**Comment by akshayat** [comment]
> I also achieved that using multi stage build, see [here](https://stackoverflow.com/a/61276740/1534925)
> 
> @simpleenigma I think you would also want to copy the conf files from build stage.
> 
> Still not sure it is the correct way or not.

BTW from that way I am getting following error. So not sure is it because of the way I included the modules or the any other issue

```
[pagespeed:error] [pid 11:tid 139839959594752] [mod_pagespeed 1.13.35.2-0 @11] Slow write operation                               on file /var/cache/mod_pagespeed/v3/abc: 88.098                              ms; configure SlowFileLatencyUs to change threshold\n
[pagespeed:error] [pid 9:tid 139839581923072] [mod_pagespeed 1.13.35.2-0 @9] Slow ReadFile operation                               on file /var/cache/mod_pagespeed/v3/abccc: 99.8                              06ms; configure SlowFileLatencyUs to change threshold\n
[pagespeed:error] [pid 9:tid 139829832574720] [mod_pagespeed 1.13.35.2-0 @9] PageSpeed Serf fetch fa                              ilure rate extremely high; only 0 of 672 recent fetches fully successful; is fetching working?
[pagespeed:warn] [pid 9:tid 139840068699904] [mod_pagespeed 1.13.35.2-0 @9] inflation failure, size=                              -1

```

**Comment by javsalgar** [comment]
Hi,

We were considering in adding the Pagespeed module to our apache image but not enabled by default. This way users could enable it in case they consider it necessary. Would that work for you?

**Comment by simpleenigma** [comment]
@akshayat I had copied the conf for pagespeed to my local folder and made changes while developing this image.

@javsalgar that would be wonderful

**Comment by akshayat** [comment]
> Hi,
> 
> We were considering in adding the Pagespeed module to our apache image but not enabled by default. This way users could enable it in case they consider it necessary. Would that work for you?

Perfect

**Comment by javsalgar** [comment]
Great. Please note that this is not a critical feature so I cannot guarantee an ETA. However, I will update the ticket when we have more updates.

**Comment by javsalgar** [comment]
Not stale

**Comment by marcosbc** [comment]
@akshayat Just wanted to let you know that we've finally implemented this feature! It was added to `bitnami/apache:2.4.43-debian-10-r66`, although it is disabled by default.

To enable it, uncomment the following lines in `httpd.conf`:

```
#Include conf/pagespeed.conf
#Include conf/pagespeed_libraries.conf
```

You can do that either by [extending the image](https://github.com/bitnami/bitnami-docker-apache#extend-this-image) or mounting your own `httpd.conf` configuration file with the proper configuration.
