### ISSUE TITLE
a2enmod not found

### ISSUE THREAD

**Issue by robots4life** [bitnami/bitnami-docker-apache#102]
In the running Bitnami Apache container as normal or root user I am missing `a2enmod`.
`a2enmod not found` when I try to do `a2enmod http2` for example.

How can I use `a2enmod` and `a2dismod` and the other a2* with the Bitnami Apache container please?
https://manpages.debian.org/buster/apache2/index.html
https://manpages.debian.org/stretch/apache2/index.html

**Comment by rafariossaa** [comment]
Hi @robots4life ,
  Our container does not provide those tools, one of the reasons is because the structure is different and those tools would not work.
  If you need to enable a mod you can add the `LoadModule` directive in the httpd.conf or mount your own httpd.conf as indicated [here](https://github.com/bitnami/bitnami-docker-apache#user-content-full-configuration)

**Comment by robots4life** [comment]
Thank you.
