### ISSUE TITLE
Unable to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by thraxarious** [bitnami/bitnami-docker-apache#84]
We're trying to test this out for eventual deployment and I'm having a heck of a time following the documentation here.

Was trying originally on Centos, but gave that up after not being able to find the relevant packages to make things work.

But I seem to be at a strange place, either the installation was halted too early before and its stuck or I am missing a part.

Welcome to the Bitnami apache container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
INFO  ==> Starting apache...
nami    ERROR Unable to start com.bitnami.apache: AH00112: Warning: DocumentRoot [/app/zymkey/] does not exist
AH00526: Syntax error on line 12 of /opt/bitnami/apache/conf/vhosts/zk.conf:
SSLCACertificateFile: file '/etc/ssl/zk/ca-chain.pem' does not exist or is empty

I have a self signed cert already installed in the base Apache server, and its working, but I am not sure what the heck this is asking for, and the "guide" is extremely light on documentation on what is needed.

Also, it talks about an install image or something? But I have yet to find anything of the sort.

To be clear, this is a very basic install of Ubuntu Server 16.04, and was following the documentation on:

https://community.zymbit.com/t/openssl-apache-setup-generating-csr/107

**Comment by juan131** [comment]
Hi @thraxarious 

The error below is complaining about being unable to locate the certificate you configured on your **zk.conf** file. 

```
AH00526: Syntax error on line 12 of /opt/bitnami/apache/conf/vhosts/zk.conf:
SSLCACertificateFile: file '/etc/ssl/zk/ca-chain.pem' does not exist or is empty
```

I guess you wrote that configuration file and mounted it on your container as described on the section [Adding custom virtual hosts](https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts). 

In order to use your own certificate, I recommend you to follow the section [Using custom SSL certificates](https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates) location them on the recommended directory instead of using **/etc/ssl/**.
