### ISSUE TITLE
regression: VOLUME reintroduced, makes extending difficult

### ISSUE THREAD

**Issue by ymajoros** [bitnami/bitnami-docker-apache#93]
In commit `0f076df04a80c89ea108b071fcf8f6894c7d6c67`, _VOLUME_ was added back in `.4/debian-9/Dockerfile`, while the _changelog_ of 2.4.12-4-r01 says this:

_The /app directory is no longer exported as a volume. This caused problems when building on top of the image, since changes in the volume are not persisted between Dockerfile RUN instructions. To keep the previous behavior (so that you can mount the volume in another container), create the container with the -v /app option._

Use case: I wanted to extend the image to create a specific image for my application, but whatever I put in /app during build disappears because of that.

**Comment by miguelaeh** [comment]
Hi @ymajoros ,
Can you detail what are you doing to persist the data? Are you using docker-compose? Did you mount a volume on that path to persist data? 
The `VOLUME` directive is just to mark the directory as a mount point, for example is useful for Docker Swarm, but actually you can mount a volume wherever you want and you should not have problems.

**Comment by ymajoros** [comment]
I extended your image to download an archive with _curl_, extract it to /app. Because /app is now a volume, its content is gone in the next step.

I ended up doing from a plain alpine image, which works perfectly in comparison:
```FROM alpine:latest

RUN apk add --no-cache curl apache2 apache2-proxy sed

RUN sed -i '/LoadModule rewrite_module/s/^#//g' /etc/apache2/httpd.conf

ARG VERSION

COPY followup-ui/vhost.conf /etc/apache2/conf.d/followup.conf

RUN mkdir /var/www/app && cd /var/www/app && curl -fO http://someserver/repository/maven-releases/be/vdab/followup/followup-ui/${VERSION}/followup-ui-${VERSION}-ng.tgz && tar xvfz followup-ui-${VERSION}-ng.tgz && rm followup-ui-${VERSION}-ng.tgz

CMD httpd && tail -F /var/log/apache2/*
```

**Comment by miguelaeh** [comment]
Hi @ymajoros ,
You need to download the curl before the `VOLUME` directive. Have in mind you will need to create the directory with `mkdir`. If you create the content inside the volume after the `VOLUME` directive it will not appear. 
>The `docker run` command initializes the newly created volume with any data that exists at the specified location within the base image. 

That means, if the data is created on the base image after the `VOLUME` directive, it will not appear after the `docker run`, if the data is created before the `VOLUME` directive it will appear because it will be copy to the volume.

**Comment by ymajoros** [comment]
No, that doesn't work anymore because the VOLUME line has been added back to your base image. So, extending it, my RUN step isn't actually doing anything (files are gone after that step). Seems that problem was there in the past, and the VOLUME line had been removed, but it's been introduced back without comment end of last month, so it's a regression.

**Comment by miguelaeh** [comment]
Yes, I know that the directive was added again. It is necessary for Docker Swarm because it need to be marked as mount point. But I tested and you can modify the Dockerfile if you create the files before the directive. You can refer to the [official docs](https://docs.docker.com/engine/reference/builder/#volume)

**Comment by ymajoros** [comment]
It's absolutely not required for Docker Swarm, you can just declare volumes in docker-compose.yml: https://docs.docker.com/compose/compose-file/#volumes (the only difference is that it won't create one if you don't specify it, which is basically expected).

OTOH, you cannot ADD files before VOLUME if you extend bitnami-docker-apache. Basically, VOLUME in Dockerfile makes this image unsuitable for extension for html application packaging.

**Comment by miguelaeh** [comment]
Oh, sorry, I see what you are talking about, I thought you cloned the repo to modify the Dockerfile instead of use the `FROM` directive I guess you are using to extend right?
I will discuss this point with the team, it has been discussed multiple time for other issues. Thank you for reporting. I will ping you with a response.

**Comment by jojoob** [comment]
I use the image (or rather images based on this image) in a swarm environment and don't use ssl for these containers (I use an nginx proxy with ssl in front). Because of the VOLUME instruction an anonymous volume is created each time the task is recreated or moved to another swam node...
I would be happy if the VOLUME instruction gets removed.

**Comment by juan131** [comment]
Hi everyone!

Just want to let you know that we removed the `VOLUME` directive in the latest revision of the Bitnami Docker Apache image: **2.4.39-r117**

Check the new Dockerfile at: https://github.com/bitnami/bitnami-docker-apache/blob/master/2.4/debian-9/Dockerfile

Could you give it a try?
